version: '3.8'
services:
  backend:
    build:
      context: ./backend/src
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - ./config.ts:/app/config.ts
    environment:
      - PORT=4000
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    restart: unless-stopped 